(cl:defpackage autopilot_bridge-msg
  (:use )
  (:export
   "<STATUS>"
   "STATUS"
   "<ATTITUDE>"
   "ATTITUDE"
   "<HEARTBEAT>"
   "HEARTBEAT"
   "<YPS>"
   "YPS"
   "<RALLYPOINT>"
   "RALLYPOINT"
   "<GEODOMETRY>"
   "GEODOMETRY"
   "<LLA>"
   "LLA"
   "<GEOPOSEWITHCOVARIANCE>"
   "GEOPOSEWITHCOVARIANCE"
   "<AUTOPILOTMSG>"
   "AUTOPILOTMSG"
   "<WEATHERDATA>"
   "WEATHERDATA"
   "<PARAMPAIR>"
   "PARAMPAIR"
   "<TAKEOFF>"
   "TAKEOFF"
   "<WAYPOINT>"
   "WAYPOINT"
   "<GEOPOINT>"
   "GEOPOINT"
   "<FENCEPOINT>"
   "FENCEPOINT"
   "<GEOPOSE>"
   "GEOPOSE"
  ))

