/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/acs_ros_ws/src/autopilot_bridge/srv/ReqPrevNMsgs.srv
 *
 */


#ifndef AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H
#define AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autopilot_bridge/AutoPilotMsg.h>

namespace autopilot_bridge
{
template <class ContainerAllocator>
struct ReqPrevNMsgsResponse_
{
  typedef ReqPrevNMsgsResponse_<ContainerAllocator> Type;

  ReqPrevNMsgsResponse_()
    : msgs()  {
    }
  ReqPrevNMsgsResponse_(const ContainerAllocator& _alloc)
    : msgs(_alloc)  {
    }



   typedef std::vector< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> >::other >  _msgs_type;
  _msgs_type msgs;




  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReqPrevNMsgsResponse_

typedef ::autopilot_bridge::ReqPrevNMsgsResponse_<std::allocator<void> > ReqPrevNMsgsResponse;

typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse > ReqPrevNMsgsResponsePtr;
typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse const> ReqPrevNMsgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/odroid/acs_ros_ws/src/autopilot_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b83e643d817366665bc7d105b0ffecd6";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb83e643d81736666ULL;
  static const uint64_t static_value2 = 0x5bc7d105b0ffecd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/ReqPrevNMsgsResponse";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AutoPilotMsg[] msgs\n\
\n\
\n\
================================================================================\n\
MSG: autopilot_bridge/AutoPilotMsg\n\
uint32  seq\n\
string  text\n\
";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ReqPrevNMsgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "msgs[]" << std::endl;
    for (size_t i = 0; i < v.msgs.size(); ++i)
    {
      s << indent << "  msgs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.msgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H
